language: php

sudo: false

matrix:
  include:
    - php: hhvm-3.19
      sudo: required
      dist: trusty
      group: edge
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-dist

script: make test
